name: Deploy Flutter Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Remove pre-installed Flutter
      run: sudo rm -rf /opt/hostedtoolcache/flutter
    
    - name: Setup Flutter
      uses: flutter-actions/setup-flutter@v2
      with:
        version: '3.22.0'
        cache: false
    
    - name: Check Flutter and Dart version
      run: |
        flutter --version
        dart --version
    
    - name: Clean Flutter project
      run: flutter clean
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build Web
      run: |
        flutter build web \
          --dart-define=STREAM_API_KEY=${{ secrets.STREAM_API_KEY }} \
          --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
          --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
          --dart-define=FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} \
          --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
          --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
          --release
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web 